
ECHO Date: %DATE%
ECHO Time: %TIME%
echo %TIME: =0%

SET TIMEHR=%TIME: =0%
ECHO %TIMEHR%

SET DTVARYEAR=%DATE:~10%
ECHO %DTVARYEAR%

SET DTVARDAY=%DATE:~7,2%
ECHO %DTVARDAY%

SET DTVARMONTH=%DATE:~4,2%
ECHO %DTVARMONTH%

SET DTVARTIMEHRS=%TIMEHR:~0,2%
ECHO %DTVARTIMEHRS%

SET DTVARTIMEMIN=%TIME:~3,2%
ECHO %DTVARTIMEMIN%

SET DTVARTIMESEC=%TIME:~6,2%
ECHO %DTVARTIMESEC%

SET DTVAR=%DTVARYEAR%-%DTVARMONTH%-%DTVARDAY%--%DTVARTIMEHRS%-%DTVARTIMEMIN%

ECHO %DTVAR%



robocopy E:\Shares\engineering z:\ /S /E /COPY:DAT /DCOPY:DAT /MT:1 /W:0 /R:1 /XO /XX > E:\logs\copyENG-%DTVAR%.log
